# Generated by Django 5.2.1 on 2025-07-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthbackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='show_author_name',
            field=models.BooleanField(default=True),
        ),
    ]
