# Generated by Django 5.2.1 on 2025-07-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthbackend', '0004_remove_question_answer_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapistBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('therapy_type', models.CharField(choices=[('individual', 'Individual'), ('student', 'Student'), ('couple', 'Couple')], max_length=20)),
                ('pronouns', models.CharField(blank=True, max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender_identity', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('prefer_not_say', 'Prefer not to say')], max_length=20)),
                ('occupation', models.CharField(max_length=255)),
                ('reason_for_therapy', models.TextField()),
                ('preferred_time_slot', models.DateTimeField()),
                ('payment_completed', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
            ],
        ),
    ]
