# Generated by Django 5.2.1 on 2025-07-16 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthbackend', '0005_therapistbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('specialization', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('available_days', models.CharField(max_length=100)),
                ('available_time', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='therapistbooking',
            name='location',
        ),
        migrations.RemoveField(
            model_name='therapistbooking',
            name='specialization',
        ),
        migrations.AlterField(
            model_name='therapistbooking',
            name='therapy_type',
            field=models.CharField(choices=[('student', 'Student'), ('couple', 'Couple'), ('cbt', 'Cognitive Behavioral Therapy'), ('mindfulness', 'Mindfulness Therapy'), ('talk', 'Talk Therapy')], max_length=20),
        ),
        migrations.AddField(
            model_name='therapistbooking',
            name='therapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='healthbackend.therapist'),
        ),
    ]
